### ISSUE TITLE
Wrong .xml code generation

### ISSUE THREAD

**Issue by ferologics** [jhen0409/generator-rnb#1]
All instances of "app name" have "<>" characters, or these characters are used in the wrong places

in consequence the rnb generator is not usable

just git clone the RNB instead

**Comment by jhen0409** [comment]
Fixed by https://github.com/jhen0409/generator-rnb/commit/c4ebf4388e441540783ec87ff749f1386f1cfb4e, will publish new version.

**Comment by jhen0409** [comment]
Published in `v0.2.0`, please check. :)
